project_id = "yxmirlnvrrintrvicqic"

[functions.whatsapp-bot]
verify_jwt = false

[functions.manage-waiter-auth]
verify_jwt = true

[functions.check-delivery-delays]
verify_jwt = false

[functions.external-orders-ingest]
verify_jwt = false

[functions.mercadopago-create-payment]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.mercadopago-public-key]
verify_jwt = false

[functions.mercadopago-cancel-payment]
verify_jwt = false
